name: "Build"

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os:
          - windows-latest
          - macOS-latest
          - ubuntu-latest
        nimversion:
          - stable
          - devel
          - 1.2.12
    name: ${{ matrix.os }} - ${{ matrix.nimversion }}
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
         submodules: recursive
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nimversion }}
      - run: nim --version
      - name: Refresh packages + install dependencies
        run: |
          nimble refresh
          nimble install -d
      - name: Run all tests
        run: nimble test
